### ISSUE TITLE
Unsaved product option field cannot be removed

### ISSUE THREAD

**Issue by sacha-vto** [aimeos/ai-admin-jqadm#94] opened 2019-07-11 08:52 UTC
Hello,

In the product panel, before an option is saved, the inputs and the button .act-delete don't belong to a tr.config-item

![aimeos_product_option_delete](https://user-images.githubusercontent.com/43008978/61036451-6cc34000-a3c9-11e9-89e4-2e1c0d9e347d.jpg)
![aimeos_product_option_delete_2](https://user-images.githubusercontent.com/43008978/61036548-9c724800-a3c9-11e9-8c65-915f1ffc9a38.jpg)
(the first option is saved, the second is a fresh one)

The result is that deleteConfigLine is not executed
https://github.com/aimeos/ai-admin-jqadm/blob/master/admin/jqadm/themes/admin.js#L332

Best regards

**Comment by aimeos** [comment] 2019-07-11 09:26
Thank you for your bug report. The problem is fixed with commit https://github.com/aimeos/ai-admin-jqadm/commit/b315f7174e72544c5c54c87c8f0fc5c274e6e335 and will be available in the next releases of the stable and LTS branches too.

**Closed by aimeos** 2019-07-11 09:26 UTC
