### ISSUE TITLE
Impossible to get the review form for selection product's order

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-admin-jqadm#282] opened 2023-10-01 09:30 UTC
**Environment**
Version - 2023.07
Integration - Laravel
System - Windows10

**Describe the bug**
There is no review form on the Account page for selection product's orders.

**To Reproduce**
1. Create a "Select product" item with 2-3 variants.
2. Purchase it.
3. Go to the Account section - there is no form available for reviewing this order.
4. Change the type of the product you just created from "Select" to "Article."
5. Purchase it again.
6. Return to the Account section - now there is a review form.
Why wasn't there a review form available for the "Select" product?

**Comment by akropivko** [comment] 2023-10-01 09:40
Video comment for the previous description 
https://github.com/aimeos/ai-admin-jqadm/assets/66216139/87d0fc4e-1dc2-4076-ad42-ff6b8ffd5072

**Comment by aimeos** [comment] 2023-10-02 13:43
Thanks for noticing!
The problem is that the variant article isn't in a category so it's not found here:
https://github.com/aimeos/ai-client-html/blob/master/src/Client/Html/Account/Review/Standard.php#L116-L119

Solving that is not difficult but the next problem is that there's no image displayed if only the parent product contains the images and we currently think about how we can solve that in an elegant way.

**Comment by aimeos** [comment] 2023-10-05 08:07
The problem is fixed now in dev-master and 2023.10.x-dev and will be part of the next release.

**Comment by akropivko** [comment] 2023-10-05 09:48
thanks

**Comment by akropivko** [comment] 2023-10-06 20:14
Can I ask you: have you also fixed the following bundle problem? If a review was created and then approved in the backend for one of the child articles, then the review is shown on the catalog detail page for the **child** article **only** (if the child article is in any category)? And the **parent** article don't have the review on the catalog detail page?

**Comment by aimeos** [comment] 2023-10-07 07:45
It makes no sense to give a review of a single article to the bundle parent which contains several articles, doesn't it?

**Comment by akropivko** [comment] 2023-10-07 08:33
Allow me to disagree here. Let's consider a scenario where we have furniture from a famous brand. Each product item comes in various color variations. In essence, these pieces of furniture are identical, differing only in color. Naturally, a buyer would want to read reviews about the same furniture in any color. It makes no difference what the color of the furniture is if it's made from the same material and has the same sizes, etc. By the way, this isn't just a theory; it's an actual project requirement.

Nonetheless, could you advise me on the best approach to display reviews from variants on the parent frontend review block?

**Comment by aimeos** [comment] 2023-10-07 10:38
You've used the term **bundle** before and for "bundle" products, it still makes no sense. For "selection" products with variant articles this is different indeed! There it makes sense to attach the reviews to the selection products instead of the variant articles. This commit should assign reviews to selection products instead of variant articles: https://github.com/aimeos/ai-client-html/commit/b7b001a8984a2fc32e5c1de841a67a50f16bdf5a

Can you check?

**Comment by akropivko** [comment] 2023-10-07 12:34
My appologize. "Bundle problem" = "related problem".
I tried to test it but it was unsuccesful:
Updating to 2023.10.x-dev by composer ( "aimeos/aimeos-laravel": "2023.10.x-dev",) cause sql error 
![Screenshot_46](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/3a94d239-ef1d-4ded-aee8-812b55118a20)
Copy-paste result from https://github.com/aimeos/ai-client-html/commit/b7b001a8984a2fc32e5c1de841a67a50f16bdf5a is impossible for me since my file version is not the same as edited there.
Copy-paste result from https://github.com/aimeos/ai-client-html/commit/4826da5fd4b61162cd196742fd7b380e937ba6f1?diff=split does not show the ordered "select" product in the profile page review section. 
Is there another way to quickly get the update?

**Comment by akropivko** [comment] 2023-10-08 19:25
Could you please tell me if any work continues in this direction? Currently, I've applied all these commits:
![Screenshot_47](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/6ccdd54d-c8b1-4581-bd23-b9270f529cd5)

However, there is still no item available for review. There seems to be something in the dump...
![Screenshot_48](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/41fea055-7498-46bc-91e3-506cb3191fca)
... but a) it doesn't display on the Account Review page, and b) I've checked the dump, and it doesn't have all the items I've just purchased."

**Comment by akropivko** [comment] 2023-10-11 16:36
Thanks! Okay, now it works on the Account Review page, but there are still no review counts and review items on the frontend (Catalog Details). If you're going to fix it, it seems that the following steps are needed (please let me know if I'm wrong):

1. Run through the product_item dump to retrieve the review quantities for all child articles:

![Screenshot_51](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/4ec1f6db-6105-4761-b1bb-1b8479d49118)

2. Update the content of data-productid with the IDs of all child items:

![Screenshot_52](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/a2e8ea22-d993-46d9-8224-60c4b63e20a3)

3. Modify the catalog-detail.js to fetch reviews for all these IDs:
![Screenshot_53](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/fc825ee5-8c83-4144-9c68-a48e187e259a)

**Comment by akropivko** [comment] 2023-10-11 17:25
... and now the Attribute Map in the Catalog Filter is empy - 
![Screenshot_54](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/5bd7935b-4dd0-4b21-a64a-54caf3553162)

![Screenshot_55](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/ae3acc8d-8da0-439a-8d36-0dca16490698)

**Comment by aimeos** [comment] 2023-10-12 08:12
Keep in mind that you have to check reviews in the backend and set them to "enabled" to show them in the frontend if you don't set `controller/frontend/review/status = 1` to show all reviews without any checking before.

**Closed by aimeos** 2023-10-12 08:12 UTC

**Comment by akropivko** [comment] 2023-10-13 12:25
I've just created a [pull request](https://github.com/aimeos/ai-client-html/pull/209/commits) to fix this on the frontend
