### ISSUE TITLE
Stock level force to null for variants when a "select" type product item was copied by "Save and copy" btn

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-admin-jqadm#275] opened 2023-09-19 18:49 UTC
**Environment**
Version - 2023.07
Integration - Laravel
System - Windows10

**Describe the bug**
Stock level force to null for variants when a "select" type product item was copied by "Save and copy" btn

**To Reproduce**
1. Create a select type product item with a couple of its variants.
2. Set Stock level values of the variants to infinity.
3. Open the initial select type product created before and click Save and copy btn.
4. Check the Stock level of the initial variants again - null.

**Expected behavior**
Stock levels of initial variants should remain the same.

**Comment by aimeos** [comment] 2023-09-19 22:06
Sorry, don't understand where the problem is. Can you show us the potential problem with screenshots?

**Comment by akropivko** [comment] 2023-09-20 12:27
sure!
![ai](https://github.com/aimeos/ai-admin-jqadm/assets/66216139/09931acf-244c-44ea-8ce8-0bd1118157c7)

**Comment by aimeos** [comment] 2023-09-21 21:29
Thanks for the video, it was very helpful to understand the issue :-)
The problem was that stock level items has been moved from the old to the new variant articles and this is fixed now in dev-master and 2023.07.x-dev

**Closed** 2023-09-22 11:42 UTC
