### ISSUE TITLE
In BE, Moving a category to first position in cat tree not possible

### ISSUE THREAD

**Issue by rowild** [aimeos/ai-admin-jqadm#118] opened 2020-06-15 07:56 UTC
In the BE, having a category tree like the one shown in the screenshots, it is not possible to move any category to the very first place in the category tree. Instead, after save/reload the category will always be placed as the very last one.

(It works, when moved to the 2nd place.)

TYPO3 9.5.19, aimeos 20.4, php 7.3.18

![move-cat](https://user-images.githubusercontent.com/213803/84631680-13736300-aeee-11ea-93a3-fa9d3cd6ccf0.jpg)

**Comment by aimeos** [comment] 2020-06-15 08:32
This is the behavior of the jqtree library that may differ from TYPO3 but is not a problem

**Comment by rowild** [comment] 2020-06-15 08:50
What? Why is this not a problem? What about UI/UX?

**Comment by aimeos** [comment] 2020-06-15 09:12
You can move the categories to the first place but you have to moved the mouse pointer between the root node and the first entry until the line between both items appear that shows the the node will be inserted there. It's not possible to drop the node at the root node and expect that it's inserted at the first place

**Comment by rowild** [comment] 2020-06-15 09:26
Please have a look at my screenshots: from what I see, the left half shows a correct positioning of "Körpertheater". Why shouldn't it stay there, if it shows the correct positioning? And even if, why , if not possible to be put as the first category in list, is it afterwards moved to the last position?

These problems do not appear, when moving to another (second, third) position. IMO, if there is a problem with the first position, there should be at least some kind of visible/informational feedback.

But to say "this is not a problem" is by all means not true, if I may say so.

**Comment by aimeos** [comment] 2020-06-15 09:30
OK, now I see. You moved the node to the first position and it was placed correctly but after reloadin the page, the change was not saved. Sorry for the misunderstanding. I can confirm that this is a problem and have to investigate what happens here.

**Comment by rowild** [comment] 2020-06-15 09:35
BTW: this is true for all first-position options, even for deeper sub levels...

**Comment by aimeos** [comment] 2020-06-15 09:39
Yes, it happens in subcategories too

**Comment by aimeos** [comment] 2020-06-15 17:38
The problem is fixed in dev-master, 2020.04.x-dev and 2019.10.x-dev. Can you confirm?

**Comment by rowild** [comment] 2020-06-15 17:59
I can confirm that your solution works fine for both 20.4 and "2019.10.x-dev as 19.10.7" (via aimeos distribution). 

Thank you very much!!!
The fix looks way more complex then I have imagined!!

Is there anywhere a review place, where I should place a "+1"?

**Comment by aimeos** [comment] 2020-06-15 19:05
All fine, thank you very much for your help! :-)

**Closed by aimeos** 2020-06-15 19:06 UTC
